<?
	$title = '';
	if (isset($dirTree)) foreach ($dirTree as $node) $title .= "$node[name] » ";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="<?= phob::$media ?>/style.css" type="text/css" media="screen" />
	<title><?= $siteName ?> :: <?= $title ?></title>
</head>
<body>
<div id="page">
	<div id="header">
		<h1><a href="<?= phob::$base ?>"><?= $siteName ?></a></h1>

		<div id="navigation">
		<? if (isset($dirTree)) foreach ($dirTree as $item) { ?>
			<a href="<?= $item['path'] ?>"><?= $item['name'] ?></a> »
		<?php } ?>
		</div>
	</div>

	<div id="main">
		<h1><?= $message ?></h1>
		<br />
	</div>

	</div>
</div>
</body>
</html>