<?
	$title = '';
	foreach ($dirTree as $node) $title .= "$node[name] » ";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="<?= $css ?>style.css" type="text/css" media="screen" />
	<title><?= $siteName ?> :: <?= $title ?></title>
</head>
<body>
<div id="page">
	<div id="header">
		<h1><a href="<?= $this->root ?>"><?= $siteName ?></a></h1>

		<div id="navigation">
		<? foreach ($dirTree as $item) { ?>
			<a href="<?= $item['path'] ?>"><?= $item['name'] ?></a> »
		<?php } ?>
		</div>
	</div>

	<div id="main">
	<?
		$i = 1;
		foreach ($photos as $photo) {
			if ($photo['type'] == 'dir') {
	?>
			<a href="<?= $photo['path'] ?>" class="item dir">
				<span><?= $photo['name'] ?></span>
			</a>
	<?		} else { ?>
			<a href="<?= $photo['path'] ?>" class="item photo">
				<img src="<?= $photo['thumb'] ?>" />
				<span><?= $photo['name'] ?></span>
			</a>
	<?
			}
			
			if ($i++ % 6 == 0) {
				echo '<br style="clear: left" />';
			}
		}
	?>
	<br style="clear: left" /><br />
	</div>
</div>
</body>
</html>