<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="<?= $css ?>style.css" type="text/css" media="screen" />
	<title><?= $siteName ?> :: <?= $dirTree[count($dirTree) - 1]['name'] ?></title>
</head>
<body>
<div id="page">
	<div id="header">
		<h1><a href="<?= $this->root ?>"><?= $siteName ?></a></h1>

		<div id="navigation">
		<? foreach ($dirTree as $item) { ?>
			<a href="<?= $item['path'] ?>"><?= $item['name'] ?></a> »
		<?php } ?>
		</div>
	</div>

	<div id="main">
		<table>
		<tr>
			<td class="thumb left">
			<? if ($prev !== false) { ?>
			<a href="<?= $prev['path'] ?>"><span>Předchozí</span>
				<img src="<?= $prev['thumb'] ?>"/>
			</a>
			<? } ?>
			</td>

			<td class="photo">
				<?= !empty($label) ? "<div class='label'>$label</div>" : ''; ?>
				<a href="<?= $photoUrl ?>">
					<img src="<?= $photoUrl ?>"/>
				</a>
			</td>

			<td class="thumb right">
			<? if ($next !== false) { ?>
			<a href="<?= $next['path'] ?>"><span>Následující</span>
				<img src="<?= $next['thumb'] ?>"/>
			</a>
			<? } ?>
			</td>
		</tr>
		<?php if (!empty($exif)) { ?>
		<tr>
			<td colspan="3">
			<table class="exif">
			<?php foreach ($exif as $key => $val) { ?>
				<tr>
					<th><?= $key ?></th>
					<td><?= $val ?></td>
				</tr>
			<?php } ?>
			</table>
			</td>
		</tr>
		<?php } ?>
		</table>
	</div>
	<br style="clear: left" /><br />
	</div>
</div>
</body>
</html>