<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="<?php echo $css ?>style.css" type="text/css" media="screen" />
	<title><?php echo $siteName ?> :: <?php echo $dirTree[count($dirTree) - 1]['name'] ?></title>
</head>
<body>
<div id="page">
	<div id="header">
		<h1><a href="<?php echo $this->root ?>"><?php echo $siteName ?></a></h1>

		<div id="navigation">
		<?php foreach ($dirTree as $item) { ?>
			<a href="<?php echo $item['path'] ?>"><?php echo $item['name'] ?></a> »
		<?php } ?>
		</div>
	</div>

	<div id="main">
		<table>
		<tr>
			<td class="thumb left">
			<?php if ($prev !== false) { ?>
			<a href="<?php echo $prev['path'] ?>"><span>Předchozí</span>
				<img src="<?php echo $prev['thumb'] ?>"/>
			</a>
			<?php } ?>
			</td>

			<td class="photo">
				<?php echo !empty($label) ? "<div class='label'>$label</div>" : ''; ?>
				<a href="<?php echo $photoUrl ?>">
					<img src="<?php echo $photoUrl ?>"/>
				</a>
			</td>

			<td class="thumb right">
			<?php if ($next !== false) { ?>
			<a href="<?php echo $next['path'] ?>"><span>Následující</span>
				<img src="<?php echo $next['thumb'] ?>"/>
			</a>
			<?php } ?>
			</td>
		</tr>
		<?php if (!empty($exif)) { ?>
		<tr>
			<td colspan="3">
			<table class="exif">
			<?php foreach ($exif as $key => $val) { ?>
				<tr>
					<th><?php echo $key ?></th>
					<td><?php echo $val ?></td>
				</tr>
			<?php } ?>
			</table>
			</td>
		</tr>
		<?php } ?>
		</table>
	</div>
	<br style="clear: left" /><br />
	</div>
</div>
</body>
</html>